samples: config/samples.tsv
units: config/units.tsv

ref:
  # Ensembl species name
  species: homo_sapiens
  # Ensembl release (make sure to take one where snpeff data is available, check 'snpEff databases' output)
  release: 100
  # Genome build
  build: GRCh38

trimming:
  activate: False

pca:
  activate: True
  labels:
    # columns of sample sheet to use for PCA
    - condition

diffexp:
  # contrasts for the deseq2 results method
  contrasts:
    A-vs-B:
      - A
      - B
  model: ~condition

params:
  cutadapt-pe: ""
  cutadapt-se: ""
  star: "--outSAMtype BAM Unsorted"